# Generated by Django 4.0.3 on 2022-04-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='description',
            new_name='title',
        ),
    ]
