# Generated by Django 4.0.3 on 2022-04-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_rename_description_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedimage',
            name='image',
            field=models.ImageField(max_length=10240, upload_to=''),
        ),
    ]
